### ISSUE TITLE
Request for Update: Missing Code and Dependencies in CausalRCA

### ISSUE THREAD

**Issue by beifangqiuer** [phamquiluan/RCAEval#35]
Dear phamquiluan，

I hope this message finds you well. First of all, I want to express my appreciation for the great work you've done on the RCAEval project. It has been incredibly helpful for my research and projects.

However, I've encountered a couple of issues while working with the code:

It seems that the code for CausalRCA is missing in the repository. If possible, could you please update the repository with the complete code?

I've noticed that several dependencies appear to be missing from the requirements.txt file. This has made it a bit challenging to set up the environment correctly.

Additionally, could you update the code to include training and inference using a private dataset?

I would be grateful if you could address these issues at your earliest convenience. Your work has been invaluable, and these updates would greatly enhance the usability of the project.

Thank you for your time and assistance.

Best regards,

**Comment by phamquiluan** [comment]
Hi @beifangqiuer, now you can find the implementation for CausalRCA here: https://github.com/phamquiluan/RCAEval/blob/main/RCAEval/e2e/causalrca.py 

The current dependency works perfectly fine for it. Please note that this method is pretty slow..

**Comment by beifangqiuer** [comment]
Thank you for your reply, it helped me a lot!
