### ISSUE TITLE
Request for the latest Baro code

### ISSUE THREAD

**Issue by beifangqiuer** [phamquiluan/RCAEval#37]
Hello,

The open-source Baro code seems to be inconsistent with the description in your paper. Could you please provide the latest version of the code?

Sincerely

**Comment by phamquiluan** [comment]
> seems to be inconsistent

@beifangqiuer could you please make this clearer, I'm not sure what do you mean by say it's inconsistent?

**Comment by beifangqiuer** [comment]
In the code, Baro seems to be a purely statistical method. It calculates statistical values using normal data, then normalizes the anomalous data, and uses the z-score to compute the maximum value of the anomalous columns and sort them.

**Comment by beifangqiuer** [comment]
In the code, Baro seems to be a purely statistical method. It calculates statistical values using normal data, then normalizes the anomalous data, and uses the z-score to compute the maximum value of the anomalous columns and sort them.

**Comment by beifangqiuer** [comment]
It seems that the nsigma algorithm you provided in your code follows a similar approach.

**Comment by phamquiluan** [comment]
@beifangqiuer BARO includes two components: Multivariate BOCPD and RobustScorer. You can see in this paper: https://dl.acm.org/doi/pdf/10.1145/3660805.

In this repo, I focus on RCA part, so I only use RobustScorer for BARO without using the anomaly detection component (Multivariate BOCPD). 

> Baro seems to be a purely statistical method.

You're right! There are three major RCA approaches: statistical analysis, topology graph-based, and causal graph-based. BARO is a statistical analysis approach.

> It seems that the nsigma algorithm you provided in your code follows a similar approach.

You're right again. NSigma uses mean and std. Meanwhile, BARO uses median and IQR, it's less sensitive to the anomaly detection time.

**Comment by beifangqiuer** [comment]
Okay, thank you, I understand. We are currently following up on your RCAEval project and would like to apply it to industrial fault root cause analysis.

**Comment by phamquiluan** [comment]
@beifangqiuer I would love to help. Let me know if the team needs one more hand.

p/s: the reviewers keep asking for "real-world data".. I have a PTSD with them 😭

**Comment by beifangqiuer** [comment]
Haha, alright, all the best, let's keep up the good work together!

**Comment by beifangqiuer** [comment]
Hello, we ran the RCAEval code you provided, and encountered an error with easyrca. It didn't produce any results, only a single message output, and we're not sure what's going on. With cloudranger, the issue is with the input data, which needs to be invertible, but our data doesn't meet this requirement, so it resulted in an error. In the microrank and tracerca algorithms, the data columns are hardcoded, making it unusable for our data. Could you please help provide code that can adapt to any type of time series data? Thank you sincerely.

**Comment by phamquiluan** [comment]
Thank you for the feedback @beifangqiuer. 

Now I'm doing the following tasks (in order): 
- Add the reproducibility document for this paper: https://arxiv.org/abs/2412.17015
- Add document to create/extend new dataset #19 
- Add document to create/extend new method #20 

I think the current problem is that I haven't provide the document on create a new dataset. I will provide them when I fix #19. And I will provide some functions to check the data to see if they are appropriate.

**Comment by beifangqiuer** [comment]
Link: https://www.phmsociety.org/events/conference/phm/16/data-challenge

We are currently trying to use the open-source PHM dataset. However, this dataset does not include fault root causes, so we need to simulate and generate fault root causes. Our current method for generating fault root causes is as follows:

1. First, we use a tree model, such as XGBoost, to predict the target column AVG_REMOVAL_RATE and train a model using normal data.
2. Then, we simulate the occurrence of an abnormal fault by suddenly increasing and then decreasing the values of a certain column in the dataset over several consecutive timestamps.
3. We use this generated data to perform inference with the trained tree model. We consider the data where the prediction error of AVG_REMOVAL_RATE exceeds 5% as successful anomaly injections, and the column where we introduced the fault is considered the root cause for this data.
4. The extracted data after this process is used as the dataset for the RCA model.
5. Finally, I trained and inferred using over 20 algorithms and found that Baro performed the best, identifying half of the faults in Top 1 and all within Top 5. However, the model requires an anomaly injection time (inject_time) to ensure that the data before is normal and the data after is abnormal. In real industrial scenarios, it is difficult to provide such data, as inject_time is generally not directly available. Anomaly injection time can only be detected by the model, and my self-designed method for detecting anomaly injection time may not be accurate, leading to suboptimal results for half of the data.
6. Methods based on topology and causal graphs tend to rank certain fixed columns at the top, which confuses me. Causal inference methods find it difficult to identify the column I injected.
7. Do you have a detailed summary of which algorithms in RCAEval are suitable for which types of fault root causes? Are you familiar with the types of faults in time series data in the industry?
8. I only simulated one type of fault here, which seems to be suitable for statistical methods. However, statistical methods are sensitive to the anomaly injection time, which cannot be confirmed in real industrial applications.

I hope you can address my concerns. We are collaborating with a large semiconductor company and hope to apply RCAEval to the semiconductor industry, especially causal inference methods, to promote the development of the integrated circuit industry.

**Comment by phamquiluan** [comment]
> Finally, I trained and inferred using over 20 algorithms and found that Baro performed the best, identifying half of the faults in Top 1 and all within Top 5. However, the model requires an anomaly injection time (inject_time) to ensure that the data before is normal and the data after is abnormal. In real industrial scenarios, it is difficult to provide such data, as inject_time is generally not directly available.

Hi @beifangqiuer, you can try Multivariate BOCPD to identify the `inject_time` automatically. The code is available here: https://github.com/phamquiluan/baro

**Comment by beifangqiuer** [comment]
Thank you, I will continue to follow up on the RCAEval project!
