### ISSUE TITLE
Number of fault types in RE3

### ISSUE THREAD

**Issue by aron123** [phamquiluan/RCAEval#43]
Hi,

The documentation says, that in dataset RE3, there are 5 fault types ranging from F1 to F5, however, RE3-TT contains a folder named "ts-route-service_f6".

Is the label wrong, or there are 6 fault types in the dataset?

**Comment by phamquiluan** [comment]
Thanks for the report @aron123! There is only 5 fault type. I will check this f6 and let you know soon. 

Actually, I'm in the process of refining this RE3 dataset with better label and provide a better code of processing this dataset. Please stay tune!

**Comment by phamquiluan** [comment]
Hi @aron123, it's a F3: Missing function call. 

<img width="882" alt="image" src="https://github.com/user-attachments/assets/5c52f53d-e92d-4366-b9b2-c72ec5adffc1" />

However, I'm working on this dataset to perfect it. I recommend you to work on RE1 and RE2 first, and wait for me :sob:

**Comment by aron123** [comment]
Thank you!
